const nodes = [
  {
    id: "step1",
    type: "group",
    position: { x: 0.0, y: 0.0 },
    style: { width: 170, height: 140 },
    data: { label: "STEP1", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986626",
    type: "input",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step1",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "1588452116296986646",
    type: "input",
    position: { x: 10.0, y: 80.0 },
    style: null,
    data: { label: "sample", processId: "2" },
    parentNode: "step1",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "step2",
    type: "group",
    position: { x: 250.0, y: 0.0 },
    style: { width: 170, height: 140 },
    data: { label: "STEP2", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986627",
    type: "default",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step2",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "1588452116296986647",
    type: "default",
    position: { x: 10.0, y: 80.0 },
    style: null,
    data: { label: "sample", processId: "2" },
    parentNode: "step2",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "step3",
    type: "group",
    position: { x: 500.0, y: 0.0 },
    style: { width: 170, height: 140 },
    data: { label: "STEP3", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986629",
    type: "default",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step3",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "1588452116296986649",
    type: "default",
    position: { x: 10.0, y: 80.0 },
    style: null,
    data: { label: "sample", processId: "2" },
    parentNode: "step3",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "step4",
    type: "group",
    position: { x: 750.0, y: 0.0 },
    style: { width: 170, height: 140 },
    data: { label: "STEP4", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986632",
    type: "default",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step4",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "1588452116296986652",
    type: "default",
    position: { x: 10.0, y: 80.0 },
    style: null,
    data: { label: "sample", processId: "2" },
    parentNode: "step4",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "step5",
    type: "group",
    position: { x: 1000.0, y: 0.0 },
    style: { width: 170, height: 140 },
    data: { label: "STEP5", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986635",
    type: "default",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step5",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "1588452116296986655",
    type: "default",
    position: { x: 10.0, y: 80.0 },
    style: null,
    data: { label: "sample", processId: "2" },
    parentNode: "step5",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "step6",
    type: "group",
    position: { x: 1250.0, y: 0.0 },
    style: { width: 170, height: 180 },
    data: { label: "STEP6", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986638",
    type: "default",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step6",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "1588452116296986658",
    type: "default",
    position: { x: 10.0, y: 80.0 },
    style: null,
    data: { label: "sample", processId: "2" },
    parentNode: "step6",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "1602502320268619777",
    type: "default",
    position: { x: 10.0, y: 130.0 },
    style: null,
    data: { label: "pipette1", processId: "1602500804942082050" },
    parentNode: "step6",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "step7",
    type: "group",
    position: { x: 1500.0, y: 0.0 },
    style: { width: 170, height: 140 },
    data: { label: "STEP7", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986641",
    type: "default",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step7",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "1588452116296986661",
    type: "default",
    position: { x: 10.0, y: 80.0 },
    style: null,
    data: { label: "sample", processId: "2" },
    parentNode: "step7",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "step8",
    type: "group",
    position: { x: 1750.0, y: 0.0 },
    style: { width: 170, height: 140 },
    data: { label: "STEP8", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986644",
    type: "default",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step8",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "step9",
    type: "group",
    position: { x: 2000.0, y: 0.0 },
    style: { width: 170, height: 140 },
    data: { label: "STEP9", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986664",
    type: "default",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step9",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "step10",
    type: "group",
    position: { x: 2250.0, y: 0.0 },
    style: { width: 170, height: 140 },
    data: { label: "STEP10", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986667",
    type: "default",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step10",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "step11",
    type: "group",
    position: { x: 2500.0, y: 0.0 },
    style: { width: 170, height: 140 },
    data: { label: "STEP11", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986670",
    type: "default",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step11",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "step12",
    type: "group",
    position: { x: 2750.0, y: 0.0 },
    style: { width: 170, height: 180 },
    data: { label: "STEP12", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986673",
    type: "default",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step12",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "1588452116296986679",
    type: "default",
    position: { x: 10.0, y: 80.0 },
    style: null,
    data: { label: "empty", processId: "4" },
    parentNode: "step12",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "1602504286092767234",
    type: "default",
    position: { x: 10.0, y: 130.0 },
    style: null,
    data: { label: "pipette2", processId: "1602501018394406914" },
    parentNode: "step12",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "step13",
    type: "group",
    position: { x: 3000.0, y: 0.0 },
    style: { width: 170, height: 140 },
    data: { label: "STEP13", processId: null },
    parentNode: null,
    extent: null,
    targetPosition: "top",
    sourcePosition: "bottom"
  },
  {
    id: "1588452116296986676",
    type: "output",
    position: { x: 10.0, y: 30.0 },
    style: null,
    data: { label: "standard", processId: "1" },
    parentNode: "step13",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  },
  {
    id: "1588452116296986682",
    type: "output",
    position: { x: 10.0, y: 80.0 },
    style: null,
    data: { label: "empty", processId: "4" },
    parentNode: "step13",
    extent: "parent",
    targetPosition: "left",
    sourcePosition: "right"
  }
];

export default nodes;
