spring:
  h2:
    # 开启console 访问 默认false
    console:
      enabled: true
      settings:
        # 开启h2 console 跟踪 方便调试  默认 false
        trace: false
        # 允许console 远程访问 默认false
        web-allow-others: true
      # h2 访问路径上下文
      path: /h2-console
  sql:
    init:
      platform: h2
      # 初始化数据表 DDL
      schema-locations:
        - classpath:db/schema-runtime-h2.sql
      mode: EMBEDDED
      continue-on-error: true
  datasource:
    dynamic:
      datasource:
        # 运行时数据源
        runtime:
          driverClassName: org.h2.Driver
          url: jdbc:h2:mem:hephaestus_runtime;MODE=MySQL;DATABASE_TO_LOWER=TRUE
          username: sa
          password: sa