CREATE TABLE `hephaestus_instance` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增id',
    `experiment_id` bigint(20) DEFAULT NULL COMMENT '实验ID',
    `workflow_run_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '实验实例ID',
    `instance_title` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '实验名称',
    `start_storage_id` bigint(20) DEFAULT NULL COMMENT '实验起始位置ID',
    `end_storage_id` bigint(20) DEFAULT NULL COMMENT '实验结束位置ID',
    `current_storage_id` bigint(20) DEFAULT NULL COMMENT '实验当前位置ID',
    `instance_status` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '实验状态 ',
    `instance_context` json DEFAULT NULL COMMENT '实验参数',
    `current_step` json DEFAULT NULL COMMENT '当前step',
    `current_step_total` bigint(20) DEFAULT NULL COMMENT '当前step总计',
    `active_stage_id` bigint(20) DEFAULT NULL COMMENT '所在节点ID',
    `active_stage_status` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '所在节点状态',
    `instance_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `instance_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `process_id` bigint(20) DEFAULT NULL COMMENT '流程id',
    `process_record_id` bigint(20) DEFAULT NULL COMMENT '记录id',
    `create_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '修改人',
    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
    `remarks` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
    `is_deleted` tinyint(4) DEFAULT '0' COMMENT '是否 删除 0 否 1是',
    `delete_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '删除人',
    `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`) USING BTREE,
    KEY `instance_id` (`workflow_run_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `hephaestus_instance_cap` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `instance_id` bigint(20) DEFAULT NULL COMMENT '实例id',
    `process_record_id` bigint(20) DEFAULT NULL COMMENT '记录id',
    `device_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备类型',
    `device_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备key',
    `open_cap_time` datetime DEFAULT NULL COMMENT '开盖时间',
    `close_cap_time` datetime DEFAULT NULL COMMENT '关盖时间',
    `device_status` int(11) DEFAULT NULL COMMENT '状态 0 已开盖 1已关盖 默认null',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `unique_instance_id` (`instance_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `hephaestus_instance_plate` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `experiment_id` bigint(20) DEFAULT NULL COMMENT '实验id',
    `experiment_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '实验名称',
    `experiment_group_id` bigint(20) DEFAULT NULL COMMENT '实验组id',
    `experiment_pool_id` bigint(20) DEFAULT NULL COMMENT '实验池id',
    `experiment_pool_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '实验池类型',
    `experiment_plate_storage_id` bigint(20) DEFAULT NULL COMMENT '实验板id',
    `process_record_id` bigint(20) DEFAULT NULL COMMENT '记录id',
    `device_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备类型',
    `device_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备key',
    `instance_id` bigint(20) DEFAULT NULL COMMENT '实例id',
    `is_consumed` tinyint(4) DEFAULT '0' COMMENT '是否消费 0 未消费 1消费',
    `consume_time` datetime DEFAULT NULL COMMENT '消费时间',
    `is_finished` tinyint(4) DEFAULT NULL COMMENT '是否完成 0 未完成 1已完成',
    `finish_time` datetime DEFAULT NULL COMMENT '完成时间',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `plate_no` int(11) DEFAULT NULL COMMENT '板序号',
    `bar_code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '条形码',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='实例板池表';


CREATE TABLE `hephaestus_instance_step` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增id',
    `instance_id` bigint(20) DEFAULT NULL COMMENT '实验实例ID',
    `instance_status` int(11) DEFAULT NULL COMMENT '状态',
    `pool_type` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '池类型',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `finish_time` datetime DEFAULT NULL COMMENT '完成时间',
    `plate_no` int(11) DEFAULT NULL COMMENT '板序号',
    `batch_no` int(11) DEFAULT NULL COMMENT '批次号',
    `process_record_id` bigint(20) DEFAULT NULL COMMENT '记录id',
    `step_total` bigint(20) DEFAULT NULL COMMENT 'step总和',
    `step1_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step1_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step1_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step1_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step1_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step1_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step1_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step1_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step2_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step2_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step2_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step2_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step2_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step2_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step2_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step2_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step3_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step3_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step3_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step3_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step3_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step3_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step3_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step3_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step4_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step4_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step4_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step4_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step4_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step4_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step4_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step4_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step5_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step5_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step5_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step5_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step5_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step5_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step5_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step5_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step6_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step6_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step6_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step6_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step6_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step6_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step6_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step6_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step7_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step7_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step7_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step7_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step7_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step7_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step7_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step7_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step8_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step8_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step8_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step8_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step8_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step8_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step8_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step8_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step9_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step9_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step9_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step9_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step9_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step9_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step9_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step9_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step10_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step10_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step10_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step10_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step10_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step10_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step10_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step10_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step11_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step11_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step11_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step11_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step11_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step11_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step11_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step11_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step12_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step12_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step12_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step12_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step12_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step12_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step12_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step12_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step13_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step13_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step13_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step13_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step13_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step13_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step13_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step13_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step14_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step14_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step14_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step14_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step14_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step14_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step14_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step14_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step15_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step15_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step15_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step15_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step15_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step15_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step15_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step15_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step16_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step16_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step16_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step16_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step16_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step16_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step16_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step16_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step17_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step17_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step17_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step17_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step17_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step17_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step17_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step17_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step18_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step18_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step18_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step18_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step18_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step18_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step18_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step18_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step19_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step19_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step19_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step19_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step19_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step19_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step19_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step19_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step20_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step20_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step20_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step20_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step20_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step20_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step20_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step20_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step21_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step21_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step21_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step21_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step21_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step21_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step21_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step21_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step22_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step22_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step22_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step22_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step22_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step22_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step22_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step22_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step23_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step23_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step23_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step23_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step23_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step23_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step23_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step23_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step24_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step24_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step24_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step24_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step24_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step24_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step24_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step24_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step25_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step25_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step25_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step25_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step25_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step25_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step25_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step25_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step26_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step26_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step26_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step26_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step26_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step26_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step26_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step26_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step27_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step27_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step27_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step27_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step27_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step27_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step27_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step27_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step28_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step28_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step28_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step28_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step28_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step28_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step28_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step28_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step29_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step29_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step29_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step29_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step29_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step29_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step29_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step29_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step30_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step30_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step30_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step30_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step30_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step30_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step30_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step30_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step31_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step31_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step31_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step31_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step31_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step31_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step31_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step31_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    `step32_key` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤类型',
    `step32_name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤名称',
    `step32_create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `step32_start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `step32_end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `step32_waiting_second` bigint(20) DEFAULT NULL COMMENT '等待时间',
    `step32_duration_second` bigint(20) DEFAULT NULL COMMENT '持续时间',
    `step32_interval_second` bigint(20) DEFAULT NULL COMMENT '间隔时间',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `unique_instance_id` (`instance_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='实例步骤表';


CREATE TABLE `hephaestus_instance_task` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增id',
    `device_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '0' COMMENT '设备类型',
    `device_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备key',
    `device_key_range` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '可用deviceKey范围，逗号分割',
    `priority` int(11) DEFAULT '111' COMMENT '设备锁优先级 1 高  11 中 111 低',
    `device_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备表device_id',
    `task_id` bigint(20) DEFAULT NULL COMMENT '任务id',
    `task_status` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'task状态 await等待，running：进行，finished：完成，failed：失败',
    `task_command` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务命令',
    `task_parameter` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务参数',
    `task_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务名称',
    `task_request_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '请求id',
    `task_error_message` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '异常信息',
    `instance_id` bigint(20) DEFAULT NULL COMMENT '实例id',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `update_priority_time` datetime DEFAULT NULL COMMENT '更新时间',
    `timeout_second` bigint(20) DEFAULT NULL COMMENT '超时时间',
    `next_task_expire_duration_second` bigint(20) DEFAULT '-1' COMMENT '到达下一个任务最大间距时间 单位秒 -1 没有限制',
    `step_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'step key',
    `step_value` bigint(20) DEFAULT NULL COMMENT 'step 值',
    `experiment_pool_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '实验池类型',
    `task_no` int(11) DEFAULT NULL COMMENT '任务编号',
    `plate_no` int(11) DEFAULT NULL COMMENT '板序号',
    `process_record_id` bigint(20) DEFAULT NULL COMMENT '记录id',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务表';


CREATE TABLE `hephaestus_instance_task_result` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `instance_id` bigint(20) DEFAULT NULL COMMENT '实例id',
    `task_id` bigint(20) DEFAULT NULL COMMENT '任务id',
    `process_record_id` bigint(20) DEFAULT NULL COMMENT '记录id',
    `step_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '步骤的key',
    `execution_status` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '执行状态',
    `execution_result` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '执行结果',
    `version` int(11) DEFAULT NULL COMMENT '版本号',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `hephaestus_resource_bottleneck` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `device_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备类型',
    `pool_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '池类型',
    `calculating_time` datetime DEFAULT NULL COMMENT '计算时间',
    `required_time_of_sum` bigint(20) DEFAULT NULL COMMENT '计算需要的时间总和',
    `wait_task_count` bigint(20) DEFAULT NULL COMMENT 'Wait在瓶颈资源的所有任务数量',
    `wait_time_duration` bigint(20) DEFAULT NULL COMMENT 'Wait在等待瓶颈资源的所有任务等待时间',
    `execution_time` bigint(20) DEFAULT NULL COMMENT '瓶颈资源执行时间',
    `before_task_count` bigint(20) DEFAULT NULL COMMENT '到达瓶颈资源前的所有任务 * （到达瓶颈资源前所需的时间 + 瓶颈资源执行时间）',
    `average_time` bigint(20) DEFAULT NULL COMMENT '瓶颈资源当前执行剩余时间（有多个则取平均值）',
    `device_count` bigint(20) DEFAULT NULL COMMENT '瓶颈资源数量',
    `device_with_plate_number` bigint(20) DEFAULT NULL COMMENT '瓶颈资源带板数',
    `process_record_id` bigint(20) DEFAULT NULL COMMENT '记录id',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资源瓶颈表';


CREATE TABLE `hephaestus_resource_task` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增id',
    `process_record_id` bigint(20) DEFAULT NULL COMMENT '流程记录id',
    `device_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '0' COMMENT '设备类型',
    `device_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备key',
    `device_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备表device_id',
    `step_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'stepKey',
    `task_id` bigint(20) DEFAULT NULL COMMENT '任务id',
    `task_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务名称',
    `task_status` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'task状态 await等待，running：进行，finished：完成，failed：失败',
    `task_command` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务命令',
    `task_parameter` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务参数',
    `task_request_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '请求id',
    `task_error_message` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '异常信息',
    `task_response_message` json DEFAULT NULL COMMENT '响应内容',
    `stage_id` bigint(20) DEFAULT NULL COMMENT '阶段id',
    `stage_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '阶段名称',
    `experiment_id` bigint(20) DEFAULT NULL COMMENT '实验id',
    `instance_id` bigint(20) DEFAULT NULL COMMENT '实例id',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    `task_duration` bigint(20) DEFAULT NULL COMMENT '耗时',
    `task_timeout_second` bigint(20) DEFAULT NULL COMMENT '任务运行超时时间',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `unique_instance_task` (`instance_id`,`task_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='设备资源请求返回表';


CREATE TABLE `hephaestus_resource_status` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `process_record_id` bigint(20) DEFAULT NULL COMMENT '流程记录id',
    `device_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备key',
    `resource_status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '资源状态',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `device_key` (`device_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资源状态';


CREATE TABLE `hephaestus_resource_storage_status` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `process_record_id` bigint(20) DEFAULT NULL COMMENT '流程记录id',
    `storage_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'storage key',
    `device_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备key',
    `instance_id` bigint(20) DEFAULT NULL COMMENT '实例id',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `storage_key` (`storage_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='存储状态';


CREATE TABLE `hephaestus_process_record` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `process_id` bigint(20) DEFAULT NULL COMMENT '流程id',
    `process_status` int(11) DEFAULT NULL COMMENT '流程状态 0:预定义,5:初始化,10:运行,15:完成,20:回收板位',
    `process_name` varchar(255)  DEFAULT NULL COMMENT '流程名称',
    `agent_application_name` varchar(255) DEFAULT NULL  COMMENT '启动应用名称',
    `create_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '修改人',
    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
    `remarks` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
    `is_deleted` tinyint(4) DEFAULT '0' COMMENT '是否 删除 0 否 1是',
    `delete_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '删除人',
    `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `hephaestus_instance_labware_consume` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `experiment_id` bigint(20) DEFAULT NULL COMMENT '实验id',
    `experiment_name` varchar(255) DEFAULT NULL COMMENT '实验名称',
    `instance_labware_id` bigint(20) DEFAULT NULL COMMENT '实例耗材Id',
    `process_id` bigint(20) DEFAULT NULL COMMENT '流程id',
    `iteration_id` bigint(20) DEFAULT NULL COMMENT '通量id',
    `iteration_no` bigint(20) DEFAULT NULL COMMENT '通量id',
    `instance_id` bigint(20) DEFAULT NULL COMMENT '实例id',
    `process_record_id` bigint(20) DEFAULT NULL COMMENT '流程记录id',
    `is_consumed` tinyint(4) DEFAULT '0' COMMENT '是否消费 0 未消费 1消费',
    `consume_time` datetime DEFAULT NULL COMMENT '消费时间',
    `is_finished` tinyint(4) DEFAULT NULL COMMENT '是否完成 0 未完成 1已完成',
    `finish_time` datetime DEFAULT NULL COMMENT '完成时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='实例耗材消费表';


CREATE TABLE `hephaestus_instance_iteration_consume` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `iteration_id` bigint(20) DEFAULT NULL COMMENT '通量id',
  `instance_id` bigint(20) DEFAULT NULL COMMENT '实例id',
  `process_record_id` bigint(20) DEFAULT NULL COMMENT '流程记录id',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `is_consumed` tinyint(4) DEFAULT '0' COMMENT '是否消费 0 未消费 1消费',
  `consume_time` datetime DEFAULT NULL COMMENT '消费时间',
  `is_finished` tinyint(4) DEFAULT NULL COMMENT '是否完成 0 未完成 1已完成',
  `finish_time` datetime DEFAULT NULL COMMENT '完成时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通量消费情况';

CREATE TABLE `hephaestus_labware_transfer` (
   `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '移液记录ID',
   `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
   `process_record_id` bigint(20) DEFAULT NULL COMMENT '记录id',
   `plan_id` bigint(20) DEFAULT NULL COMMENT '移液计划ID',
   `source_plate` bigint(20) DEFAULT NULL COMMENT '起始板ID',
   `source_well` bigint(20) DEFAULT NULL COMMENT '起始孔ID',
   `destination_plate` bigint(20) DEFAULT NULL COMMENT '目标板ID',
   `destination_well` bigint(20) DEFAULT NULL COMMENT '目标孔ID',
   `liquid_id` bigint(20) DEFAULT NULL COMMENT '移液使用的液体ID 当transfer_type为sample时 此id 为-1',
   `source_sample_id` bigint(20) DEFAULT NULL COMMENT '起始样品ID',
   `destination_sample_id` bigint(20) DEFAULT NULL COMMENT '目标样品ID',
   `transfer_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '移液类型 liquid, sample',
   `volume` float DEFAULT NULL COMMENT '移液体积',
   `pipette_id` bigint(20) DEFAULT NULL COMMENT '移液头ID',
   `transfer_time` datetime DEFAULT NULL COMMENT '移液时间',
   `sample_transfer_method` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PARTIAL（部分）、WHOLE（全部）、MIX（混合）',
   `create_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
   `create_time` datetime DEFAULT NULL COMMENT '创建时间',
   `update_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '修改人',
   `update_time` datetime DEFAULT NULL COMMENT '修改时间',
   `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否 删除 0 否 1是',
   `delete_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '删除人',
   `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
   PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移液记录表';
